### ISSUE TITLE
Review on UI changes (Task 98, already merged)

### ISSUE THREAD

**Issue by markrudtke** [asepart/amosss182#82]
@longpdo 

[98_review.pdf](https://github.com/asepart/amosss182/files/2092142/98_review.pdf)

Generally:

1. every clickable object should be clearly evident. This applies to most of the objects, using the change of mouse cursor to hand. It doesn’t apply to the new icons (add/edit/delete/logout). This should be adjusted to keep consistency.

2. we have to distinguish between „delete user from app“ and „remove user from project“. For that I had adjusted the confirmation message accordingly (DELETE vs. REMOVE). The appropriate icons should also be differentiated like that - to not confuse the admins with the same icon used for two different actions -> change icon of „remove user from project“ to something that represents „remove“ (maybe something like a red arrow)

3. you removed the back buttons, that is ok, since the browser’s back button is working now. But now this is also affecting the „tabs“ (Projects/Users and ProjectTickets/ProjectUsers), which are handled as different pages currently. This drastically worsens the navigation through the WebApp and is not a normal behavior for „back“ -> The „tabs“ should be implemented as real tabs to improve the navigation. I will try to implement that in the next sprint.

TicketChat:

4. „added refresh page after sending a message“ - ok

5. „cleared text input field after sending a message“ - ok

6. „send button only useable after entering a message - avoiding messages without text“ - ok

7. „added usability feature: send via 'Enter' key“ - not working properly (according to previous point), because the admin is able to send a message without text by using ‚Enter’

ProjectAdd:

8. „fixed bug: add button clickable even without inputing data“ - still not working properly. Entering only an entryKey enables the add button. This could result in a project without name, which makes no sense.

9. „fixed bug: text from before was still in input line“ - working for clicking on „add“ after entering text. Not working for clicking on „cancel“ after entering text.

TicketCreate and UserAdd:

10. „fixed bug: texts from before was still in input lines“  - working for clicking on „add“ after entering text. Not working for clicking on „cancel“ after entering text.

Other relevant changes:

11. „replaced buttons with icons (home, logout, add, edit, delete)“ - ok (supposing that are free icons)

**Comment by longpdo** [comment]
Okay, thanks for insight!

to 1. Yeah, I also noticed that problem. What i figured out that the icons having a URL attached to them have the change mouse to hand. The icons without this change don't have them since those are associated with popups (thats why the home button which links to project list has this change and add/edit/delete which opens up a popup doesn't)

to 2. Yeah, thats a good suggestion. Lets see what the rest says in the meeting.

to 3. That wasn't caused by the removing of the back buttons but due to URL linking. That is why the different tabs are handled as different pages since they are right now as this enables the user to directly access the Projects tab or the Users tab from an URL/bookmark.

7-10. I've fixed them locally and I will commit the fixes during the day.

11. Yeah actually free but I still have to check something else. I report on that issue directly in the next meeting.

**Comment by longpdo** [comment]
to 1. I just found a fix for that..gonna commit them soon on a new branch.

**Comment by markrudtke** [comment]
1. That is correct. But I think you can change the mouseover event easily.
3. Yeah. But removing the back buttons **forces** the admin to use the browser's back button which is just not suitable for navigation as long as we have this "tabs" handled as different pages. I think we have two option here: Add the back buttons again, or change the tab handling (which I would prefer, since this only will disable bookmarking the userlist). We should discuss this in the upcoming meeting.
7-10. Great!
